In [3]:
import pandas as pd

# Woking with JSON

In [4]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [5]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.0406
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.7270
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.9040
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,4.1800
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,2.6400
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.1770
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.2150
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.2840
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-05,1770249601,0.2840

# Working with SQL

In [15]:
import mysql.connector
print("ok")

ok

In [16]:
conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="vaishu789",
    database="testdb"
)

print("Connected successfully")

Connected successfully

In [18]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS recipes (
    id INT PRIMARY KEY,
    cuisine VARCHAR(50),
    ingredients TEXT
)
""")

print("Table created")

Table created

In [21]:
import pandas as pd

df = pd.read_json("train.json")
print(len(df))

39774

In [22]:
for _, row in df.iterrows():
    cursor.execute(
        "INSERT IGNORE INTO recipes (id, cuisine, ingredients) VALUES (%s, %s, %s)",
        (int(row["id"]), row["cuisine"], str(row["ingredients"]))
    )

conn.commit()
print("All data inserted")

All data inserted

In [25]:
cursor.execute("SELECT COUNT(*) FROM recipes")
result = cursor.fetchone()

print("Total rows:", result[0])

Total rows: 39774